export const LOAD_BOOKS_START = "LOAD_BOOKS_START"
export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS"
export const LOAD_BOOKS_FAILURE = "LOAD_BOOKS_FAILURE"

export const LOAD_MORE_BOOKS_START = "LOAD_MORE_BOOKS_START"
export const LOAD_MORE_BOOKS_SUCCESS = "LOAD_MORE_BOOKS_SUCCESS"
export const LOAD_MORE_BOOKS_FAILURE = "LOAD_MORE_BOOKS_FAILURE"

export const LOAD_CATEGORIES_START = "LOAD_CATEGORIES_START"
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS"
export const LOAD_CATEGORIES_FAILURE = "LOAD_CATEGORIES_FAILURE"



export const ADD_TO_CART = "ADD_TO_CART"
export const FETCH_BOOK_BY_ID = "FETCH_BOOK_BY_ID"

export const SET_FILTER = "SET_FILTER"
export const CLEAR_FILTER = "CLEAR_FILTER"

export const SEARCH_BOOK = "SEARCH_BOOK"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const CHECK_OUT = "CHECK_OUT"
export const CLEAR_CART = "CLEAR_CART"
